#!/bin/sh

# Script runner for AoC 2022 python solutions
# Usage:
# ./run [-t] [DAY]
#
# If run without a DAY argument, runs all solutions in the project.
# If run with a DAY argument, runs all solutions from that day.
# Solution directories must be named as double-digit integers.
# DAY can be specified as a single- or double-digit integer.
# Solution files must be named in the form `solution*.py`.
# Each day's directory is expected to contain an `input.txt`
#   file that contains the puzzle input for that day.
# If `-t` is specified, uses `test.txt` as input instead of `input.txt`

export TIME="--- finished in %E ---"
run_day() {
	cd "$1"
	if [ "$TEST" = 1 ]; then
		MSG="Testing"
		INPUT="test.txt"
	else
		MSG="Running"
		INPUT="input.txt"
	fi
	echo "----- $MSG day $1 -----"
	for file in solution*.py; do
		echo "--- File $file ---"
		time python "$file" < $INPUT
	done
	cd ..
}

if [ "$1" = "-t" ]; then
	export TEST=1
	shift 
fi

if [ "$#" -gt 0 ]; then
	day="$1"
	if echo "$day" | grep -q '^[1-9]$'; then
		day=0"$day"		
	fi
	run_day "$day"
else
	for dir in *; do
		if [ -d "$dir" ]; then
			run_day "$dir"
			echo
		fi
	done
fi
