#!/bin/sh

# Script runner for AoC 2022 python solutions
# Usage:
# ./run [-t] [DAY]
# ./run -i
#
# If run without a DAY argument, runs all solutions in the project.
# If run with a DAY argument, runs all solutions from that day.
# Solution directories must be named as double-digit integers.
# DAY can be specified as a single- or double-digit integer.
# Solution files must be named in the form `solution*.py`.
# Each day's directory is expected to contain an `input.txt`
#   file that contains the puzzle input for that day.
# If `-t` is specified, uses `test.txt` as input instead of `input.txt`
# The `-i` flag runs the program in user interractive mode

export TIME="--- finished in %E ---"
run_day() {
	cd "$1"
	if [ "$TEST" = 1 ]; then
		MSG="Testing"
		INPUT="test.txt"
		ARGS='-t'
	else
		MSG="Running"
		INPUT="input.txt"
		ARGS=''
	fi
	echo "----- $MSG day $1 -----"
	for file in solution*.py; do
		echo "--- File $file ---"
		time python "$file" $ARGS < $INPUT
	done
	cd ..
}

if [ "$1" = "-t" ]; then
	export TEST=1
	shift 
elif [ "$1" = "-i" ]; then
	echo -n "Day (1-25): "
	read day
	echo -n "Test? (y/N): "
	read t
	if [ "$t" = "y" ] || [ "$t" = "Y" ]; then
		export TEST=1
	fi
	shift
fi

if [ -n "$1" ]; then
	day="$1"
fi

if [ -n "$day" ]; then
	if echo "$day" | grep -q '^[1-9]$'; then
		day=0"$day"		
	fi
	run_day "$day"
else
	for dir in *; do
		if [ -d "$dir" ]; then
			run_day "$dir"
			echo
		fi
	done
fi
